### ISSUE TITLE
Ввод данных

### ISSUE THREAD

**Issue by Tako-San** [Tako-San/circuits#1]
Написать ввод данных с помощью *flex* и *bison*. Ввод может производиться **как из файла так и из консоли**. 

Формат ввода:
```
p1 -- p2, r; eV
```
Здесь p1, p2 -- узлы, r -- сопротивление, e - ЭДС источника

Например:
```
1 -- 2, 4.0;
1 -- 3, 10.0;
1 -- 4, 2.0; -12.0V
2 -- 3, 60.0;
2 -- 4, 22.0;
3 -- 4, 5.0;
```

**Comment by derzhavin3016** [comment]
Лексер:
* Разобраться с INT, DOUBLE
* Убрать `\n` из WS
* `DOUBLE -> {{INT}+ | 0}.{DIGIT}+`

**Comment by derzhavin3016** [comment]
Грамматика:
* Убрать EOF
* `float -> double`
* множественное раскрытие line
* сократить названия
