### ISSUE TITLE
Матрица. Уровень 2.

### ISSUE THREAD

**Issue by Tako-San** [Tako-San/circuits#2]
Второй уровень посвящен вполне практичной задаче, где многие операции для матриц найдут своё применение. 
Также он (возможно) познакомит вас с матрицами инцидентности графов.

Вам задана электрическая цепь в следующем формате:

```
p1 -- p2, r; eV
```

Здесь p1, p2 -- узлы, r -- сопротивление, e - ЭДС источника.

Вам нужно найти токи в рёбрах.

Знак при токе это его направление относительно ребра графа. То есть то текущий от 2 к 1 имеет в ребре 
```1 -- 2``` знак минус и т.д.

Формат ответа:

```
1 -- 2: -0.442958 A
1 -- 3: -0.631499 A
1 -- 4: -1.07446 A
2 -- 3: -0.0757193 A
2 -- 4: 0.367239 A
3 -- 4: -0.707219 A
```
﻿

**Comment by Tako-San** [comment]
[Матрицы инцидентности графов](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D0%B0_%D0%B8%D0%BD%D1%86%D0%B8%D0%B4%D0%B5%D0%BD%D1%82%D0%BD%D0%BE%D1%81%D1%82%D0%B8#:~:text=%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D0%B0%20%D0%B8%D0%BD%D1%86%D0%B8%D0%B4%D0%B5%D0%BD%D1%82%D0%BD%D0%BE%D1%81%D1%82%D0%B8%20%E2%80%94%20%D0%BE%D0%B4%D0%BD%D0%B0%20%D0%B8%D0%B7%20%D1%84%D0%BE%D1%80%D0%BC,%D1%81%D0%BE%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D1%81%D1%82%D0%B2%D1%83%D1%8E%D1%82%20%D1%80%D0%B5%D0%B1%D1%80%D0%B0%D0%BC%2C%20%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%B8%20%E2%80%94%20%D0%B2%D0%B5%D1%80%D1%88%D0%B8%D0%BD%D0%B0%D0%BC.)

**Comment by derzhavin3016** [comment]
[Законы Кирхгофа в матричной форме](https://poznayka.org/s56134t1.html)

**Comment by derzhavin3016** [comment]
[Еще про законы Кирхгофа](https://studref.com/589943/tehnika/zakony_kirhgofa_matrichnoy_forme)

**Comment by Tako-San** [comment]
* [Поиск циклов обходом в глубину](http://neerc.ifmo.ru/wiki/index.php?title=%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5_%D0%BE%D0%B1%D1%85%D0%BE%D0%B4%D0%B0_%D0%B2_%D0%B3%D0%BB%D1%83%D0%B1%D0%B8%D0%BD%D1%83_%D0%B4%D0%BB%D1%8F_%D0%BF%D0%BE%D0%B8%D1%81%D0%BA%D0%B0_%D1%86%D0%B8%D0%BA%D0%BB%D0%B0)
* [Обход в глубину](http://neerc.ifmo.ru/wiki/index.php?title=%D0%9E%D0%B1%D1%85%D0%BE%D0%B4_%D0%B2_%D0%B3%D0%BB%D1%83%D0%B1%D0%B8%D0%BD%D1%83,_%D1%86%D0%B2%D0%B5%D1%82%D0%B0_%D0%B2%D0%B5%D1%80%D1%88%D0%B8%D0%BD)
