### ISSUE TITLE
Add dump

### ISSUE THREAD

**Issue by derzhavin3016** [Tako-San/circuits#9]
For more convenient debug, it's better to add dump of circuit in ```.dot``` file
**REQUIREMENTS**:
* junc number
* edge number
* resistance of an edge
* eds of an edge
* current of an edge
* edge's direction
* generation of a ```.png``` file on-the-fly

**Comment by Tako-San** [comment]
Метод dump() определен в классе Circuit

**Comment by derzhavin3016** [comment]
All info should be in rectangles, like at picture
![изображение](https://user-images.githubusercontent.com/37047102/111065057-bc281080-84c8-11eb-8d27-0fa9f7387a45.png)
